import type { EntityType } from "@gridlock/shared";

/** One line per sidebar card: what the unit or building is for. Shown under the name on its tooltip card. */
export const CARD_ROLE: Partial<Record<EntityType, string>> = {
  rifleman: "Cheap line infantry. Holds ground and garrisons buildings.",
  gunner: "Machine-gun infantry. Sets the bipod and mows down soldiers.",
  sniper: "Long-range marksman. Picks off soldiers, often in one shot.",
  atinfantry: "Anti-tank infantry. Punches tank sides and rear, and light armor.",
  rocketer: "Anti-tank infantry. Rockets dent tanks and burst among soldiers.",
  pyro: "Flame infantry. Burns soldiers out of cover at very short reach.",
  mortarman: "Light artillery infantry. Lobs bombs onto soldiers out of sight.",
  engineer: "Builder and mechanic. Raises defences, repairs, and salvages scrap.",
  medic: "Field healer. Closes wounds and sets broken limbs of nearby soldiers.",
  warden: "Heavy tank. Thick front plate and a long-range gun.",
  apocalypse: "Super-heavy tank. Twin guns, armor all round, and a roof CIWS.",
  ss3: "Assault gun. Strong front, no turret: turns the hull to aim.",
  jagdtiger: "Heavy tank destroyer. Longest tank gun, goes through any front.",
  feuerwirbel: "Anti-infantry flame tank. Twin gatlings also guard against air.",
  walker: "Twin-gatling walker. Shreds infantry and self-destructs near death.",
  cyborg: "Cyborg gunner. Thermal scanner spots soldiers through fog and cover.",
  cyborgcommander: "Cyborg leader. Force field, cutting laser, takes over enemy Cyborgs.",
  simunit2: "Blink-drive assassin. Knifes soldiers and clears out garrisons.",
  xenodrone: "Hive line soldier. Tough pulse carbine that raises a small wall.",
  thrall: "Cheap hive brawler. Runs down soldiers and blows up on armor.",
  lancer: "Anti-armor cyborg. Plasma lance hits tanks; heavy plating.",
  bombard: "Hive artillery soldier. Lobs big plasma rounds from long reach.",
  weaver: "Hive support. Throws energy walls, shields allies, and mends them.",
  shade: "Cloaked hive sniper. Unseen while still, picks off soldiers.",
  stalker: "Cloaking battle walker. Plasma bolts hit like a tank shell.",
  ravager: "Fast anti-infantry walker. Pulse repeater and a plasma jet.",
  behemoth: "Hive super-heavy walker. Twin disruptors, lunges, energy wall.",
  juggernaut: "Hammer-wielding giant. Smashes tanks and buildings, rises again.",
  siphon: "Mobile shield. Its walking energy dome stops incoming fire.",
  assembler: "Walking Thrall factory. Builds Thralls on its own; keep it back.",
  mawcaster: "Plasma artillery walker. Blankets soldiers and also shoots fliers.",
  leech: "Hive gunboat. Fights boats and targets along the shore.",
  lurker: "Hive submarine beast. Always submerged, bites boats and swimmers.",
  hiveark: "Hive capital ship. Plasma cannons, a huge dome, and two Wasps.",
  wasp: "Hive gunship. Hovers and blankets an area with energy bolts.",
  scourge: "Heavy hive gunship. Plasma bolts and pulse guns from the air.",
  gnat: "Hive scout flier. Sees far from high up; very fragile.",
  overseer: "Hive beam flier. Hovers over a target and burns it from above.",
  titan: "Heavy assault walker. Tank gun, rocket pods, deploys and jump-jets.",
  mammoth: "Armored troop carrier walker. Carries infantry who fire out; lays mines.",
  nebelwerfer: "Rocket artillery. Longest reach, blankets infantry in the open.",
  artillery: "Towed field gun. Long-range shells that smash infantry and buildings.",
  supply: "Supply truck. Rearms vehicles, clears mines, tows field guns.",
  gunboat: "Fast gunboat. Fights boats and targets along the shore.",
  supplyboat: "Naval supply. Rearms the Battle Ship and other vessels at sea.",
  submarine: "Torpedo submarine. Dives out of sight and strikes ships.",
  battleship: "Naval capital ship. Heavy guns bombard far ashore; CIWS for air.",
  destroyer: "Sub hunter. Sonar finds submarines, a helicopter torpedoes them.",
  lst: "Landing ship. Carries infantry and vehicles to the beach.",
  stuka: "Dive bomber. Drops a heavy bomb on ground targets.",
  fw190: "Fighter. Cannon runs that down enemy planes and pierce tank roofs.",
  bv222: "Transport flying boat. Drops paratroops, mines, or supply crates.",
  he111: "Torpedo bomber. Attacks boats and submarines from the air.",
  horten: "Reconnaissance plane. Flies high and reveals a wide area.",
  droneop: "Drone operator. Flies a quadcopter to scout or dive on targets.",
  jumpjet: "Jet-pack infantry. Flies over obstacles and fires down into cover.",
  spawnling: "Cheap, fast swarmer. Runs down soldiers but dies easily.",
  gobber: "Bloom line soldier. Spits acid; its wounds close by themselves.",
  quillback: "Anti-infantry brood. Streams quills that mow down soldiers.",
  bloater: "Anti-tank brood. Hurls acid sacs that eat into tank plate.",
  longspine: "Bloom sniper. Spears soldiers from long range; very fragile.",
  mender: "Bloom healer. Knits wounded brood closed far faster than alone.",
  skitter: "Fast raider beast. Quill stream cuts down soldiers.",
  goretusk: "Charging beast. Gores soldiers and hulls behind a thick head shield.",
  mantis: "Bloom battle beast. Acid cannon hits like a tank shell; heals.",
  bileworm: "Ambush beast. Burrows out of sight, then sprays burning acid.",
  sporemaw: "Bloom artillery. Longest reach, shreds soldiers in the open.",
  matriarch: "Bloom queen. Tank-killing acid cannon; lays Spawnlings as she goes.",
  driftjelly: "Cheap water stinger. Kills swimmers and tears at boats.",
  spineback: "Bloom gunboat. Fights boats and targets along the shore.",
  abyssray: "Bloom submarine. Dives and looses acid eels like torpedoes.",
  leviathan: "Bloom capital ship. Armored shell and a long-range acid cannon.",
  broodbarge: "Bloom transport. Carries brood and beasts to the beach.",
  moth: "Bloom scout flier. Watches a wide area from high up; fragile.",
  razorwing: "Bloom fighter. Hunts planes and rakes tank roofs with quills.",
  gasbag: "Bloom bomber. Drops acid bombs every pass, never needs rearming.",
  drifter: "Bloom hover flier. Hangs over prey and drips burning acid.",
  harpy: "Bloom torpedo flier. Drops acid eels on targets in the water.",
  dynamo: "Base power. Supplies the power your other buildings draw.",
  smelter: "Scrap income. Melts a scrap field down for a steady flow.",
  muster: "Infantry trainer. Produces your foot soldiers and specialists.",
  armory: "Vehicle factory. Builds every tank, field gun, walker, and truck.",
  airfield: "Air base. Trains planes, and rearms and repairs them on landing.",
  dock: "Naval yard. Built on water; launches boats and submarines.",
  ciws: "Anti-air gatling. Downs planes and bursts incoming rockets.",
  ram: "Anti-air rocket launcher. Hits planes and intercepts rockets.",
  bunker: "Infantry pillbox. The best cover; its garrison fires from slits.",
  tower: "Infantry watch tower. Its garrison sees far across the field.",
  tobruk: "Small sunken pit. Cheap cover, hard to hit, open to mortars.",
  casemate: "Heavy infantry fort. Twice a bunker's toughness; costly.",
  hochstand: "Timber lookout. Farthest eyes on the field, but flimsy.",
  leitturm: "Infantry fire tower. Longest reach for its garrison, with a spotlight.",
  spotlight: "Night searchlight. Lights a long cone of ground after dark.",
  mgnest: "Fixed machine gun. Sweeps an arc to stop infantry; hits aircraft.",
  pak36: "Light anti-tank gun. Holes light hulls and tank flanks.",
  pak43: "Heavy anti-tank gun. Longest straight reach, pierces any front.",
  flak: "Anti-air gun. Flak bursts hit every plane in the cloud.",
  research: "Tech lab. Unlocks heavy tanks, the Titan, and advanced ships.",
  radar: "Radar. Lights the radar panel to track unseen aircraft.",
  cyborgcentral: "Cyborg factory and uplink. Trains cyborgs and keeps them running.",
  conversion: "Hive infantry chamber. Converts bodies into the hive's foot soldiers.",
  fusionnode: "Hive energy. Adds to the energy store that runs the hive.",
  assimilator: "Hive scrap income. Breaks a scrap field down for a steady flow.",
  forge: "Xenite vehicle factory. Grows the heavy assimilators.",
  nexus: "Hive tech core. Unlocks advanced units and defences; lights radar.",
  fusioncore: "Big hive energy store. Explodes like a Titan when destroyed.",
  spineturret: "Anti-infantry turret. Self-firing pulse repeater, all round.",
  pulsespire: "Anti-tank spire. Self-firing pulse that pierces tank fronts.",
  laserfence: "Laser barrier posts. Beams burn any enemy ground unit crossing.",
  energywall: "Energy barrier. A wide curtain that blocks enemy fire and movement.",
  spawnpool: "Hive naval pool. Built on water; grows the hive's sea units.",
  aerie: "Hive air nest. Grows the hive's fliers; no runway or fuel needed.",
  lumenbulb: "Bloom power. Powers the Bloom like a Power Plant; regrows.",
  gorger: "Bloom scrap income. Chews a scrap field down for a steady flow.",
  broodnest: "Bloom infantry nest. Hatches the brood foot soldiers.",
  gestator: "Bloom beast womb. Grows the Bloom's heavy beasts.",
  braincoral: "Bloom tech core. Unlocks advanced brood and defences; lights radar.",
  tidewomb: "Bloom naval pool. Built on water; spawns the deep brood.",
  roost: "Bloom air nest. Grows the skybrood, who return to feed and heal.",
  thornspitter: "Anti-infantry turret. Self-firing quill spitter, all round.",
  bilelance: "Anti-tank turret. Self-firing acid bolt that eats tank fronts.",
  puffcap: "Anti-air turret. Spore clouds burst around enemy planes.",
  eyestalk: "Bloom lookout. Two brood in its pouch see far and fire from it.",
  husk: "Bloom bunker. Holds brood who fire from slits; regrows.",
  sandbags: "Low cover. Gives crouched and crawling infantry extra health.",
  wall: "Concrete barrier. Blocks movement and shelters units beside it.",
  greatwall: "Fortified wall. Infantry garrison it and fire from slits.",
  gate: "Wall gate. Turns two wall sections into a gate only you pass.",
};
